### ISSUE TITLE
Add Flipper gem

### ISSUE THREAD

**Issue by mgriffin** [mgriffin/castlebarac#1]
I'm gonna want to add some new features but do it quietly :)

**Comment by mgriffin** [comment]
That was nice and easy, added the flipper gem using the instructions at https://www.flippercloud.io/docs/get-started/self-hosted

**Comment by BadLilGhostie** [comment]
> I'm gonna want to add some new features but do it quietly :)

Yep quietly...not quietly enough ya tool. It's Scott Z in 1910 asshole. You stole from me and the entire hacker community is after your livelihood and everything you hold dear. By-eeee
